// Shared products data for frontend pages
const products = [
  {id:1,title:'Tailored Trench Jeans',price:189,src:'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?auto=format&fit=crop&w=1200&q=80',desc:'Structured wool-blend trench with classic lapel and modern length.',category:'Bottoms'},
  {id:2,title:'Silk Slip Dress',price:129,src:'images/dress.jpg',desc:'Bias-cut silk slip — perfect alone or layered.',category:'Dresses'},
  {id:3,title:'Cropped Knit Polo',price:79,src:'images/polo.jpg',desc:'Cotton knit with a subtle rib, cropped to pair with high waists.',category:'Tops'},
  {id:4,title:'High-rise Wide Leg',price:139,src:'images/jean.jpg',desc:'Tailored wide-leg trousers, comfortable stretch and elegant fall.',category:'Bottoms'},
  {id:5,title:'Bodycon dress',price:99,src:'images/bodycon.png',desc:'Crisp cotton shirt with a modern fit and versatile style.',category:'Dresses'},
  {id:6,title:'Leather Ankle Boots',price:159,src:'images/boots.png',desc:'Sleek leather boots with a comfortable block heel.',category:'Shoes'},
  {id:7,title:'Long Satin Skirt',price:199,src:'images/satin.png',desc:'Soft cashmere sweater with a relaxed fit and timeless design.',category:'Bottoms'},
  {id:8,title:'Pleated Mini Skirt',price:119,src:'images/plaited.png',desc:'Flowy pleated skirt that moves with you.',category:'Bottoms'},
  {id:9,title:'Wool Fedora Hat',price:89,src:'images/fedora.jpg',desc:'Stylish wool fedora to complete any outfit.',category:'Accessories'},
  {id:10,title:'Silk Scarf',price:49,src:'images/silk.jpg',desc:'Luxurious silk scarf with a vibrant print.',category:'Accessories'},
  {id:11,title:'Denim Jacket',price:109,src:'images/jacket.jpg',desc:'Classic denim jacket with a modern fit.',category:'Outerwear'},
  {id:12,title:'Leather Tote Bag',price:179,src:'images/bag.jpg',desc:'Spacious leather tote for everyday essentials.',category:'Accessories'},
  {id:13,title:'Ankle-length Chinos',price:89,src:'images/chino.jpg',desc:'Versatile chinos with a tailored fit.',category:'Bottoms'},
  {id:14,title:'Wool Blend Coat',price:249,src:'images/coat.jpg',desc:'Warm wool blend coat with a timeless silhouette.',category:'Outerwear'},
  {id:15,title:'Graphic Tee',price:39,src:'images/tee.jpg',desc:'Casual graphic tee made from soft cotton.',category:'Tops'},
  {id:16,title:'Suede Loafers',price:129,src:'images/loafers.jpg',desc:'Comfortable suede loafers with a classic design.',category:'Shoes'},
  {id:17,title:'Linen Shorts',price:69,src:'images/shorts.jpg',desc:'Lightweight linen shorts perfect for warm weather.',category:'Bottoms'},
  {id:18,title:'Wool Beanie',price:29,src:'images/beanie.jpg',desc:'Cozy wool beanie to keep you warm.',category:'Accessories'},
  {id:19,title:'Faux Fur Vest',price:149,src:'images/vest.jpg',desc:'Chic faux fur vest for layering.',category:'Outerwear'},
  {id:20,title:'Athleisure Joggers',price:89,src:'images/joggers.jpg',desc:'Comfortable joggers for a sporty look.',category:'Bottoms'},
  {id:21,title:'Wrap Dress',price:139,src:'images/wrapdress.jpg',desc:'Flattering wrap dress for any occasion.',category:'Dresses'},
  {id:22,title:'Chelsea Boots',price:159,src:'images/chelsea.jpg',desc:'Classic Chelsea boots with a modern twist.',category:'Shoes'},
  {id:23,title:'Trench Coat',price:229,src:'images/trench.jpg',desc:'Timeless trench coat with a tailored fit.',category:'Outerwear'},
  {id:24,title:'Puffer Jacket',price:199,src:'images/puffer.jpg',desc:'Warm puffer jacket for cold days.',category:'Outerwear'},
  {id:25,title:'Ribbed Tank Top',price:49,src:'images/tanktop.jpg',desc:'Versatile ribbed tank top for layering or wearing alone.',category:'Tops'},
  {id:26,title:'Corduroy Pants',price:119,src:'images/corduroy.jpg',desc:'Soft corduroy pants with a vintage vibe.',category:'Bottoms'},
  {id:27,title:'Faux Leather Jacket',price:179,src:'images/fauxleather.jpg',desc:'Edgy faux leather jacket for a bold look.',category:'Outerwear'},
  {id:28,title:'Maxi Skirt',price:129,src:'images/maxiskirt.jpg',desc:'Flowy maxi skirt with a bohemian feel.',category:'Bottoms'},
  {id:29,title:'Button-up Shirt Dress',price:119,src:'images/shirtdress.jpg',desc:'Casual button-up shirt dress for everyday wear.',category:'Dresses'},
  {id:30,title:'Espadrille Wedges',price:139,src:'images/espadrilles.jpg',desc:'Comfortable espadrille wedges for a summery look.',category:'Shoes'},
  {id:31,title:'Denim Overalls',price:149,src:'images/overalls.jpg',desc:'Classic denim overalls with a modern fit.',category:'Bottoms'},
  {id:32,title:'Fleece Hoodie',price:79,src:'images/hoodie.jpg',desc:'Cozy fleece hoodie for casual days.',category:'Tops'},
  {id:33,title:'Pleated Trousers',price:129,src:'images/pleatedtrousers.jpg',desc:'Elegant pleated trousers for a polished look.',category:'Bottoms'},
  {id:34,title:'Silk Blouse',price:159,src:'images/silkblouse.jpg',desc:'Luxurious silk blouse with a feminine silhouette.',category:'Tops'},
  {id:35,title:'Ankle Strap Heels',price:149,src:'images/anklestrap.jpg',desc:'Chic ankle strap heels for special occasions.',category:'Shoes'}
];
